graphhopper:
  # OSM input file (can be overridden at runtime)
  datareader.file: ""
  # Graph cache location
  graph.location: "graph-cache"

  # --- Routing Profiles ---
  profiles:
    - name: "car"
      custom_model_files: ["car.json"]
    - name: "truck"
      custom_model_files: ["truck.json"]

  # Speed mode (CH)
  profiles_ch:
    - profile: "car"

  # Hybrid mode (LM)
  profiles_lm: []

  # Encoded values
  # graph.encoded_values: "car_access,car_average_speed,road_access"
  graph.encoded_values: "car_access,car_average_speed,road_access,hgv,max_width,max_height,max_weight,bus_access,road_class"


  # Subnetworks
  prepare.min_network_size: 200
  prepare.subnetworks.threads: 1

  # Routing
  routing.snap_preventions_default: "tunnel,bridge,ferry"
  routing.non_ch.max_waypoint_distance: 1000000

  # Storage
  import.osm.ignored_highways: "footway,cycleway,path,pedestrian,steps"
  graph.dataaccess.default_type: "RAM_STORE"

  # Uncomment if needed:
  # datareader.preferred_language: "en"
  # max_speed_calculator.enabled: true
  # country_rules.enabled: true
  # etc...

# Dropwizard server config
server:
  # If your DW version needs it, uncomment:
  # type: default

  application_connectors:
    - type: http
      port: 8989
      bind_host: "0.0.0.0"

  admin_connectors:
    - type: http
      port: 8990
      bind_host: "0.0.0.0"

  request_log:
    appenders: []

# Logging is at top-level (sibling of `server`)
logging:
  appenders:
    - type: file
      time_zone: "UTC"
      current_log_filename: "logs/graphhopper.log"
      log_format: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
      archive: true
      archived_log_filename_pattern: "./logs/graphhopper-%d.log.gz"
      archived_file_count: 30
      never_block: true
    - type: console
      time_zone: "UTC"
      log_format: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  loggers:
    "com.graphhopper.osm_warnings":
      level: "DEBUG"
      additive: false
      appenders:
        - type: file
          currentLogFilename: "logs/osm_warnings.log"
          archive: false
          logFormat: "[%level] %msg%n"